name: Import Icons
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    name: import icons
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install npm dependencies
        run: npm install

      - name: Run main.ts script
        run: npx tsx ./src/main.ts
        env:
          FILE_KEY: ${{ secrets.FILE_KEY }}
          FIGMA_API_KEY: ${{ secrets.FIGMA_API_KEY }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: update authors
          title: "feat: import icons"
          body: "This PR imports icons from Figma"
          branch: feat/import-icons
          add-paths: "."
