on:
  push:
    branches:
      - master

jobs:
  build:
    name: import icons
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Node.js 설치
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0

      - name: Install npm dependencies
        run: npm install

      - name: Run main.ts script
        run: npx tsx ./src/main.ts
